name: jewelify
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_secure_storage: ^9.0.0
  transparent_image: ^2.0.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  photo_view: ^0.15.0
  path_provider: ^2.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Ensure this is present

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/login_illustration.png
    - assets/logo.png # Add this line to include logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
