// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkyYgb31_00KKDa54zsUFZjTa5BRVPnjg',
    appId: '1:964755396538:web:5d1b70dcf6cc9811d52f83',
    messagingSenderId: '964755396538',
    projectId: 'jewelify-49d7f',
    authDomain: 'jewelify-49d7f.firebaseapp.com',
    storageBucket: 'jewelify-49d7f.firebasestorage.app',
    measurementId: 'G-KSZ5XDBN89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRa7qRyyMCSyfPMOhSPWO07pmIpDkN-4',
    appId: '1:964755396538:android:7b65c0d61a8b1a69d52f83',
    messagingSenderId: '964755396538',
    projectId: 'jewelify-49d7f',
    storageBucket: 'jewelify-49d7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyxP4lUfi98ZZWQgyPjGM7fhSVSEe4lo',
    appId: '1:964755396538:ios:7d7c6aea7f41163fd52f83',
    messagingSenderId: '964755396538',
    projectId: 'jewelify-49d7f',
    storageBucket: 'jewelify-49d7f.firebasestorage.app',
    iosBundleId: 'com.example.jewelifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiyxP4lUfi98ZZWQgyPjGM7fhSVSEe4lo',
    appId: '1:964755396538:ios:7d7c6aea7f41163fd52f83',
    messagingSenderId: '964755396538',
    projectId: 'jewelify-49d7f',
    storageBucket: 'jewelify-49d7f.firebasestorage.app',
    iosBundleId: 'com.example.jewelifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkyYgb31_00KKDa54zsUFZjTa5BRVPnjg',
    appId: '1:964755396538:web:2056e3085f333725d52f83',
    messagingSenderId: '964755396538',
    projectId: 'jewelify-49d7f',
    authDomain: 'jewelify-49d7f.firebaseapp.com',
    storageBucket: 'jewelify-49d7f.firebasestorage.app',
    measurementId: 'G-TQ3WZ618LG',
  );

}